### ISSUE TITLE
 [Feature Request] Arduino code for Greaseweazle : adding status messages

### ISSUE THREAD

**Issue by PicoElements** [solarmon/PCB-Projects#1]
Hello.

I was testing the display messages and i noticed that no status message is displayedat start or end.
I mean a status like "Starting writing.." or "Writing ended without issues" i.e.

Could it be possible to update the code and obtain this?

Thanks for your support,
Stefano

**Comment by solarmon** [comment]
@PicoElements 

The tracker display is very 'dumb' and even though they are on the same board, there is no communication with GW. All the tracker display does is to monitor the floppy drive signals (which are controlled by GW) and display information based on that.

To display other GW related information then a communication method is required between GW and the tracker display. I would need to put in request to the GW developer to provide some form of communication or status indication method.

**Comment by solarmon** [comment]
I have discussed this with the GW developer and at the moment that the effort required to implement such a feature is justified enough at the moment.

The GW console out has all the information required by the user. The tracker display was only meant to monitor the floppy drive signals and not communicate with GW.
